# Generated by Django 4.1.7 on 2023-03-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfidTags',
            fields=[
                ('rfidTag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
